<img src="../files/misc/logo.gif" width=300/>
<img src="../files/misc/itam.JPG" width=300/>
<h1 style="color:#872325"> Numpy: Arrreglos Matriciales </h1>

In [1]:
import numpy

El principal objeto de la Librería Numpy son arreglos homogéneos multidimensionales. Es decir, es una tabla de elementos, todos con el mismo tipo e indexados por un *tuple* de enteros positivos. 

La dimensiones en numpy se llaman **ejes** (axes); el número de ejes se llama el **rango** (rank).

La clase de arreglos en NumPy se conocen como **ndarray**s o, más comunmente, **arrays**. Un `numpy.array` no es un `array.array` de la librería estándard de Python (homogénea, pero unidimensional y con menor funcionalidad).

In [2]:
arr1 = numpy.array([[1,2,3], [4,5, 1]])
arr1

array([[1, 2, 3],
       [4, 5, 1]])

Una de las principales ventajas de usar `numpy` es el poder de usar vectorización de funciones aplicadas a un `numpy.array`. Esto implica poder aplicar una función a cada `numpy.array` sin necesidad de expresar un *for loop*, lo cuál hace trabajar con este tipo de funciónes más eficientemente.

In [ ]:
%%timeit -n 10
sum([i**2 for i in range(10_000_000)])

In [ ]:
%%timeit -n 10 # 0.0392s
(numpy.arange(10_000_000) ** 2).sum()

### Propiedas Principales de `ndarray`

In [3]:
arr1 = numpy.array([[1,2,3, 4], [4,5, 1, 6], [4,4, 4, 1]])

In [4]:
arr1

array([[1, 2, 3, 4],
       [4, 5, 1, 6],
       [4, 4, 4, 1]])

In [5]:
arr1.ndim

2

In [6]:
arr1.shape

(3, 4)

In [7]:
arr1.dtype

dtype('int64')

In [8]:
arr1.data

## Creación de Ndarrays
### np.array
un `ndarray` se crea mediante la función `arrray` cuyo primer parametro es la lista (o tuple) de elementos del arreglo.

Por convención, se importa la librería numpy como `np`.

In [9]:
import numpy as np

In [10]:
np.array( [1, 2] )

array([1, 2])

In [11]:
np.array( [[3, 1, 4], [5, 6, 8]] )

array([[3, 1, 4],
       [5, 6, 8]])

In [12]:
a = np.array( [[1, 2], [3, 4]] )
a.shape

(2, 2)

In [13]:
np.array( [[1, 2], [3, 4], [5, 6]] )

array([[1, 2],
       [3, 4],
       [5, 6]])

## Operaciones y Propiedades de Numpy Arrays

In [14]:
a1 = np.array([
     [2, 4, 6],
     [3, 5, 1]
])

In [15]:
a1 + 1

array([[3, 5, 7],
       [4, 6, 2]])

In [16]:
# Elevar al cuadrado cada entrada
a1 ** 2

array([[ 4, 16, 36],
       [ 9, 25,  1]])

In [17]:
# Multiplicación entrada a entrada
a1 * a1

array([[ 4, 16, 36],
       [ 9, 25,  1]])

In [18]:
a1 += 1
a1

array([[3, 5, 7],
       [4, 6, 2]])

In [19]:
# Comparación entrada a entrada
a1 <= 3

array([[ True, False, False],
       [False, False,  True]])

### np.arange, np.linspace
Podemos crear rangos de números $[a, b)$ usando la funcion `arange` (análogo a `range` en Python)

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [22]:
# A diferencia de range, np.arange nos permite tomar pasos fraccionarios
np.arange(1, 11, 0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

Usamos la función `linspace` cuando deseamos un arreglo de $n$ elementos entre $a$ y $b$ (inclusivo); $a < b$

In [23]:
a, b = 2, 10
np.linspace(a, b, 20)

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

<h2 style="color:crimson">Ejercicio</h2>

Crea un numpy array con 100 elementos $\{x_i\}_{i=0}^{99}$ donde
$$
    x_i = i (i + 100) \ \forall \ i \in \{0, \ldots, 99\}
$$

e.g., $x_{99} = 19701$; $x_{10} = 1100$ 

## Índices

In [24]:
arr = np.arange(25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
fila, columna = 1, 2
arr[fila, columna]

7

In [27]:
# (-2, 0), (-1, 3)
filas, columnas = [-2, -1], [0, 3]
arr[filas, columnas]

array([15, 23])

Podemos seleccionar múltiples filas usando *masks*.

In [28]:
arr[[0, -1]] = 0

In [29]:
arr

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  0,  0,  0,  0]])

In [30]:
arr[[0, -1]] # equiv. arr[[0, -1], :]

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [31]:
# Podemos asignar un valor a
# ciertas dimensiones
arr[[0, -1]] = 0
arr

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  0,  0,  0,  0]])

In [32]:
arr = np.arange(25).reshape(5, 5)
random = np.random.randint(-100, -1, size=(2, 5))

In [33]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
# podemos asignar varios valores de la misma
# dimension a la que se le hizo la selección
arr[[0, -1]] = np.random.randint(-100, -1, size=(2, 5))
arr

array([[-23, -69, -80, -48, -79],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [-82, -34, -24, -83, -67]])

In [35]:
# Al igual que una lista en Python, podemos
# revertir el orden de un numpy array con índices
arr[1][::-1]

array([9, 8, 7, 6, 5])

## Broadcasting
**Broadcasting** (difusión) es la manera en que numpy manipula *arrays* con diferentes dimensiones durante operaciones aritméticas.
Para $A$, $B$, dos dimensiones son compatibles cuando

1. Son iguales;
2. Una dimensión es igual a 1.

In [36]:
A = np.arange(25).reshape(5, 5)
B = np.arange(5).reshape(1, 5)

print(A)
print(B)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[0 1 2 3 4]]


In [37]:
A * B

array([[ 0,  1,  4,  9, 16],
       [ 0,  6, 14, 24, 36],
       [ 0, 11, 24, 39, 56],
       [ 0, 16, 34, 54, 76],
       [ 0, 21, 44, 69, 96]])

In [38]:
A + B

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18],
       [15, 17, 19, 21, 23],
       [20, 22, 24, 26, 28]])

### np.zeros

In [39]:
np.zeros(shape=10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
np.zeros(shape=(2, 5, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

### np.ones

In [42]:
np.ones(shape=10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### np.triu, np.tril

In [44]:
np.triu([1, 2, 4, 6], k=0)

array([[1, 2, 4, 6],
       [0, 2, 4, 6],
       [0, 0, 4, 6],
       [0, 0, 0, 6]])

In [45]:
np.tril([1,2,4, 6], k=0)

array([[1, 0, 0, 0],
       [1, 2, 0, 0],
       [1, 2, 4, 0],
       [1, 2, 4, 6]])

### np.identity

In [46]:
# np.eye(5) regresa el mismo resultado
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<h2 style="color:crimson">Ejercicio</h2>
Crea un numpy array en $\mathbb{R}^{10\times 10}$ tal que

$$
x_{i,j} = 
\begin{cases}
    2i & \forall \ i = j \\
    0 & \forall \ i \neq j
\end{cases}
$$

Considera $i, j \in \{1, \ldots, 10\}$

### Dimensiones de numpy arrays
Los `ndarray`s son $n$ dimensionales, lo que significa que podemos crear una arreglo $n$-dimensional siguiendo la misma lógica.

In [48]:
# Dim: 1
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
# Dim: 2. Arreglamos una matriz con 4 filas y 3 columnas
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
# Dim: 3. Arreglamos dos matrices, cada una con 2 filas y 3 columnas
# (Tensor de segundo orden)
np.arange(12).reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### Métodos de un Numpy Array

In [51]:
a2 = np.random.randint(-100, 100, 10)

In [52]:
a2.min()

-98

In [53]:
a2.max()

75

In [54]:
a2.argmax()

7

In [55]:
a2.sum()

-42

In [56]:
a2.cumsum()

array([  36,  -29,  -23,  -90,  -69, -167, -165,  -90, -108,  -42])

In [57]:
from numpy.random import seed, randint
seed(42)

a3 = randint(-100, 100, size=(2, 5, 10))
a3

array([[[  2,  79,  -8, -86,   6, -29,  88, -80,   2,  21],
        [-26, -13,  16,  -1,   3,  51,  30,  49, -48, -99],
        [-13,  57, -63,  29,  91,  87, -80,  60, -43, -79],
        [-12, -52, -42,  69,  87, -86,  89,  89,  74,  89],
        [-50,   7, -46, -37,  30, -50,  34, -80, -28,  66]],

       [[-83,  31, -12, -41, -87, -92, -11, -48,  29, -17],
        [ -9,  10,  87,  98,  71, -93,  74, -66, -20,  63],
        [-51,   3,  31, -99,  33, -47,   5, -97, -47,  90],
        [ 45, -57,  61,  89, -87,  -6, -53, -86,  99,  89],
        [-61, -19,  10, -48, -77,  53,  87,  23, -60,  56]]])

In [58]:
a3.sum(axis=0)

array([[ -81,  110,  -20, -127,  -81, -121,   77, -128,   31,    4],
       [ -35,   -3,  103,   97,   74,  -42,  104,  -17,  -68,  -36],
       [ -64,   60,  -32,  -70,  124,   40,  -75,  -37,  -90,   11],
       [  33, -109,   19,  158,    0,  -92,   36,    3,  173,  178],
       [-111,  -12,  -36,  -85,  -47,    3,  121,  -57,  -88,  122]])

## Funciones en Numpy

In [59]:
a3

array([[[  2,  79,  -8, -86,   6, -29,  88, -80,   2,  21],
        [-26, -13,  16,  -1,   3,  51,  30,  49, -48, -99],
        [-13,  57, -63,  29,  91,  87, -80,  60, -43, -79],
        [-12, -52, -42,  69,  87, -86,  89,  89,  74,  89],
        [-50,   7, -46, -37,  30, -50,  34, -80, -28,  66]],

       [[-83,  31, -12, -41, -87, -92, -11, -48,  29, -17],
        [ -9,  10,  87,  98,  71, -93,  74, -66, -20,  63],
        [-51,   3,  31, -99,  33, -47,   5, -97, -47,  90],
        [ 45, -57,  61,  89, -87,  -6, -53, -86,  99,  89],
        [-61, -19,  10, -48, -77,  53,  87,  23, -60,  56]]])

In [60]:
np.unique(a3, return_counts=False)

array([-99, -97, -93, -92, -87, -86, -83, -80, -79, -77, -66, -63, -61,
       -60, -57, -53, -52, -51, -50, -48, -47, -46, -43, -42, -41, -37,
       -29, -28, -26, -20, -19, -17, -13, -12, -11,  -9,  -8,  -6,  -1,
         2,   3,   5,   6,   7,  10,  16,  21,  23,  29,  30,  31,  33,
        34,  45,  49,  51,  53,  56,  57,  60,  61,  63,  66,  69,  71,
        74,  79,  87,  88,  89,  90,  91,  98,  99])

In [61]:
# Podemos encontrar los índices dentro de un 
# numpy array usando np.where
a4 = np.array([-1, 0,  1, -2, 1, 0, -4])
a3[np.where(a3 > 0)]

array([ 2, 79,  6, 88,  2, 21, 16,  3, 51, 30, 49, 57, 29, 91, 87, 60, 69,
       87, 89, 89, 74, 89,  7, 30, 34, 66, 31, 29, 10, 87, 98, 71, 74, 63,
        3, 31, 33,  5, 90, 45, 61, 89, 99, 89, 10, 53, 87, 23, 56])

In [62]:
a5 = np.array([
    [-1, 0,   1, -2,  1,  0, -4],
    [1,  1,  -1,  2,  2, -3,  4],
])
np.where(a5 > 0)

(array([0, 0, 1, 1, 1, 1, 1]), array([2, 4, 0, 1, 3, 4, 6]))

Numpy nos permite aplicar una función a un eje en particular usando la función `np.apply_along_axis(func1d, axis, arr, *args, **kwargs)`; donde `func1d` es una función. $f:\mathbb{R}^n \to \mathbb{R}^m$, `axis` es el eje a ejecutar: *0* para cada fila de una columna dada y *1* para cada columna de una fila y; `arr` es el numpy array a manipular.

**Ejemplo: Ordenando cada fila de una columna**.

In [63]:
from numpy.random import randint, seed
seed(1643)
a3 = randint(0, 10, size=(5,4))
a3

array([[5, 9, 6, 2],
       [2, 6, 2, 7],
       [2, 7, 4, 2],
       [8, 1, 9, 7],
       [6, 4, 4, 4]])

In [64]:
np.apply_along_axis(sorted, axis=1, arr=a3)

array([[2, 5, 6, 9],
       [2, 2, 6, 7],
       [2, 2, 4, 7],
       [1, 7, 8, 9],
       [4, 4, 4, 6]])

In [65]:
# Ordenando cada columna de una fila
np.apply_along_axis(sorted, 1, a3)

array([[2, 5, 6, 9],
       [2, 2, 6, 7],
       [2, 2, 4, 7],
       [1, 7, 8, 9],
       [4, 4, 4, 6]])

**Nota**

Al usar la función `np.apply_along_axis`, numpy aplica implicitamente un for loop en python sobre el eje que decidamos. Usar `np.apply_along_axis` **no** es la manera más eficiente de realizar este tipo de operaciones. Siempre que exista una operación equivalente de python en numpy, es recomendable usar la función dentro de numpy.

Por ejemplo, el equivalente de `sorted` en python es `np.sort` en numpy

In [66]:
a3 = randint(0, 10, size=(10_000, 10_000))

In [ ]:
%%timeit -n 5
np.apply_along_axis(sorted, 0, a3);

In [ ]:
%%timeit -n 5
# Ordenando cada fila de una columna
np.sort(a3, 0);

### Ejemplo: Series tiempo AAPL

In [67]:
aapl = np.loadtxt("../files/lec08/AAPL.txt")

In [68]:
np.where(np.diff(aapl) > 0)[0]

array([  5,   6,  12,  15,  16,  19,  21,  22,  24,  25,  26,  28,  33,
        35,  36,  37,  38,  40,  42,  43,  44,  45,  46,  48,  49,  53,
        55,  56,  57,  58,  59,  62,  65,  66,  68,  69,  70,  73,  75,
        76,  77,  78,  79,  81,  82,  83,  85,  86,  87,  89,  90,  91,
        92,  94,  96,  99, 100, 102, 103, 105, 107, 110, 111, 112, 115,
       116, 122, 124, 127, 129, 130, 132, 134, 135, 138, 139, 140, 142,
       143, 147, 148, 149, 152, 154, 156, 157, 159, 160, 164, 168, 170,
       172, 175, 177, 179, 181, 182, 183, 184, 185, 186, 187, 188, 189,
       192, 193, 194, 198, 199, 201, 202, 203, 204, 206, 207, 208, 213,
       214, 216, 217, 218, 219, 220, 221, 226, 230, 232, 237, 238, 240,
       242, 244, 246, 247, 248])

In [69]:
for num, val in zip(*np.histogram(np.diff(aapl), bins="auto")):
    print(round(val), "*" * num)

-6.0 **
-6.0 *
-5.0 
-5.0 
-4.0 
-4.0 *
-3.0 **
-3.0 ******
-3.0 *
-2.0 *****
-2.0 **********
-1.0 **************
-1.0 ******************************
-0.0 ********************************************
0.0 *************************************
0.0 ***********************************
1.0 **********************
1.0 **************
2.0 *********
2.0 *******
3.0 *****
3.0 
4.0 
4.0 **
4.0 
5.0 
5.0 
6.0 
6.0 
7.0 
7.0 **
